#  © 2024 TomTom NV. All rights reserved.
#
#  This software is the proprietary copyright of TomTom NV and its subsidiaries and may be
#  used for internal evaluation purposes or commercial use strictly subject to separate
#  license agreement between you and TomTom NV. If you are the licensee, you are only permitted
#  to use this software in accordance with the terms of your license agreement. If you are
#  not the licensee, you are not authorized to use this software in any manner and should
#  immediately return or destroy it.

platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

workspace 'TomTomSDKPublicExamplesNavigation.xcworkspace'

install! 'cocoapods', warn_for_unused_master_specs_repo: false
use_frameworks!

plugin 'cocoapods-art', :sources => [
  'tomtom-sdk-cocoapods'
]

SDK_VERSION = '0.51.1'

target 'TomTomSDKPublicExamplesNavigation' do
  pod 'TomTomSDKDefaultTextToSpeech', SDK_VERSION
  pod 'TomTomSDKLocationProvider', SDK_VERSION
  pod 'TomTomSDKMapDisplay', SDK_VERSION
  pod 'TomTomSDKNavigation', SDK_VERSION
  pod 'TomTomSDKNavigationEngines', SDK_VERSION
  pod 'TomTomSDKNavigationOnline', SDK_VERSION
  pod 'TomTomSDKNavigationUI', SDK_VERSION
  pod 'TomTomSDKRoute', SDK_VERSION
  pod 'TomTomSDKRoutingCommon', SDK_VERSION
  pod 'TomTomSDKRoutePlanner', SDK_VERSION
  pod 'TomTomSDKRoutePlannerOnline', SDK_VERSION
  pod 'TomTomSDKRouteReplannerDefault', SDK_VERSION
end
