# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Buid iOS app

on:
  workflow_call:

# clear out default permissions
permissions: {}

jobs:
  build:
    name: Buid iOS app
    permissions:
      contents: read
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Add Cocoapods repository
        # Ensure we have repos dir created
        # Workaround for https://github.com/jfrog/cocoapods-art/issues/32
        run: |
          mkdir -p ~/.cocoapods/repos
          bundle exec pod repo-art add tomtom-sdk-cocoapods https://repositories.tomtom.com/artifactory/api/pods/cocoapods

      - name: Install Cocoapods dependencies
        run: bundle exec pod install

      - name: Build iOS app
        run: >
          xcodebuild
          -workspace 'TomTomSDKExamples.xcworkspace'
          -scheme 'TomTomSDKExamples'
          -destination 'platform=iOS Simulator,name=iPhone 14'
