# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Buid iOS app

on:
  workflow_call:

env:
  spm_dir: './SPM'
  cocoapods_dir: './CocoaPods'
  platform: 'iOS Simulator'
  device_name: 'iPhone 14'
  ios_version: '16.4'

# clear out default permissions
permissions: {}

jobs:
  build-spm:
    name: Buid iOS app - SPM
    permissions:
      contents: read
    runs-on: macos-13
    defaults:
      run:
        working-directory: ${{ env.spm_dir }}
    steps:
      - uses: actions/checkout@v3

      - name: Build iOS app
        run: >
          xcodebuild
          -project 'TomTomSDKExamples.xcodeproj'
          -scheme 'TomTomSDKExamples'
          -destination 'platform=${{ env.platform }},name=${{ env.device_name }},OS=${{ env.ios_version }}'

  build-cocoapods:
    name: Buid iOS app - CocoaPods
    permissions:
      contents: read
    runs-on: macos-13
    defaults:
      run:
        working-directory:  ${{ env.cocoapods_dir }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: '${{ env.cocoapods_dir }}/Gemfile'

      - name: Add Cocoapods repository
        # Ensure we have repos dir created
        # Workaround for https://github.com/jfrog/cocoapods-art/issues/32
        run: |
          mkdir -p ~/.cocoapods/repos
          bundle exec pod repo-art add tomtom-sdk-cocoapods https://repositories.tomtom.com/artifactory/api/pods/cocoapods

      - name: Install Cocoapods dependencies
        run: bundle exec pod install

      - name: Build iOS app
        run: >
          xcodebuild
          -workspace 'TomTomSDKExamples.xcworkspace'
          -scheme 'TomTomSDKExamples'
          -destination 'platform=${{ env.platform }},name=${{ env.device_name }},OS=${{ env.ios_version }}'
