# Copyright (C) 2023 TomTom NV. All rights reserved.

---

name: Quality checks

on:
  workflow_call:

jobs:
  commisery:
    name: Conventional Commits compliance
    runs-on: ubuntu-latest
    steps:
      - uses: tomtom-international/commisery-action@v2
        with:
          token: ${{ github.token }}
